[phases.setup]
nixPkgs = ['python312', 'git']

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn summarize_youtube.index:app --chdir=api --workers=1 --threads=2 --bind=0.0.0.0:$PORT"
